#This script estimates water quality values for given values
#of streamflow, using the expected values of water quality
#and uncertainty parameters generated by the MCMC script

#IMPORTANT NOTE about this script -- for extremely high/low 
#values of streamflow (out-of-range streamflow) for which no 
#actual sampled water quality observations are available, 
#this script uses the expected values and uncertainty 
#parameters associated with the highest/lowest values of 
#streamflow for which actual water quality observations 
#ARE available (min/max in-range streamflow).

#This has some implications for my results -- high/low
#estimated water quality are likely not as extreme as they
#may actually be. The credible intervals of high/low estimated
#water quality are likely narrower than they may actually be.

#The y value files generated by this script are the past and future
#estimates of water quality used in further scripts

library(tidyverse)
library(data.table)
#library(readxl)
#library(foreach)
#library(doParallel)

wq_names <- list.files("01_Data/Redone wq and flow")
#wq_names <- list.files("/blue/carpena/caseyharris/Ch2/WQ")
wq_names <- data.frame(wq_names) %>%
  filter(str_detect(wq_names, "Lithia|Morris")) %>%
  filter(str_detect(wq_names, "Alkalinity|Color|Fluoride|Iron|Manganese|Nitrogen|TOC|Phosphorus|Turbidity"))
unique(wq_names$wq_names)

max_min <- read.csv("03_Results/max_min.csv")
#max_min <- read.csv("/blue/carpena/caseyharris/Ch2/max_min.csv")

#cluster <- makeCluster(3)
#registerDoParallel(cluster)

#This actually needs to be the actual daily flows, use the right parameters from mcmc to get individual estimates of flow for each day/sim

i=4
foreach(i = 1:length(wq_names$wq_names),
        .packages=c('tidyverse', 'data.table', 'readxl')) %dopar% {
          
          title_use <- gsub(".csv", "", wq_names$wq_names[i])
          min_use <- max_min$value[max_min$title==title_use & max_min$name=="min_flow_obs_wq_2013_2022"]
          max_use <- max_min$value[max_min$title==title_use & max_min$name=="max_flow_obs_wq_2013_2022"]
          
          mcmc_summary <- fread(paste("03_Results/MCMC/", title_use, ".csv", sep=""))
          #mcmc_summary <- fread(paste0("/blue/carpena/caseyharris/Ch2/JAGS/MCMC/", title_use, ".csv", sep=""))
          
          n_obs <- length(mcmc_summary) - 1
          cal_val <- fread(paste0("01_Data/CQ/", title_use, ".csv", sep=""))
          cal_val <- cal_val %>%
            mutate(row_number = row_number())
          #what if there's duplicate flows? just take the first one
          
          j=1
          k=1
          for (j in 1:length(mcmc_summary$r)) {
            
            y_row <- data.frame()
            
            k_min = cal_val$row_number[cal_val$Q_cfs_log_round==min_use]
            k_max = cal_val$row_number[cal_val$Q_cfs_log_round==max_use]
            for (k in 1:n_obs) {
              row_exp <- as.numeric(j)
              col_exp <- as.numeric(k+1)
              y_exp_model <- as.numeric(mcmc_summary[row_exp, ..col_exp]) #the expected y value based on the C-Q model at that flow
              
              if (cal_val$Q_cfs_log_round[k]<min_use) {
                row_est <- as.numeric(j)
                col_est <- as.numeric(k_min+1)
                set.seed(j*k)
                y <- rgamma(1, mcmc_summary$r[j], mcmc_summary$r[j]/as.numeric(mcmc_summary[row_est, ..col_est])) #the estimated y based on the min obs flow
                Q_cfs_log_round_used <- cal_val$Q_cfs_log_round[cal_val$row_number==k_min]
                y_exp_alt <- as.numeric(mcmc_summary[row_est, ..col_est]) #the expected y value based on min usable flow
              } else if (cal_val$Q_cfs_log_round[k]>max_use) {
                row_est <- as.numeric(j)
                col_est <- as.numeric(k_max+1)
                set.seed(j*k)
                y <- rgamma(1, mcmc_summary$r[j], mcmc_summary$r[j]/as.numeric(mcmc_summary[row_est, ..col_est])) #the estimated y based on the max obs flow
                Q_cfs_log_round_used <- cal_val$Q_cfs_log_round[cal_val$row_number==k_max]
                y_exp_alt <- as.numeric(mcmc_summary[row_est, ..col_est]) #the expected y value based on max usable flow
              } else {
                row_est <- as.numeric(j)
                col_est <- as.numeric(k+1)
                set.seed(j*k)
                y <- rgamma(1, mcmc_summary$r[j], mcmc_summary$r[j]/as.numeric(mcmc_summary[row_est, ..col_est]))
                Q_cfs_log_round_used <- cal_val$Q_cfs_log_round[cal_val$row_number==k]
                y_exp_alt <- as.numeric(mcmc_summary[row_est, ..col_est]) #the expected y value based on actual flow
              }
              
              y_new <- data.frame("sim"=j, 
                                  "Q_cfs_log_round"=cal_val$Q_cfs_log_round[k], 
                                  "Q_cfs_log_round_used"=Q_cfs_log_round_used,
                                  "y"=round(y, 5),
                                  "y_exp_model"=round(y_exp_model, 5),
                                  "y_exp_alt"=round(y_exp_alt, 5))
              y_row <- y_row %>%
                bind_rows(y_new)
              
            }
            
            y_row <- as.data.table(y_row)
            class(y_row)
            
            if (j==1) {
              #write.table(y_row, paste("C:/Users/cshar/OneDrive - University of Florida/Online_diss_files/Ch2/Large files/Results/y/", title_use, ".csv", sep=""), row.names=FALSE)
              write.table(y_row, paste("/blue/carpena/caseyharris/Ch2/Results/y/", title_use, ".csv", sep=""), row.names=FALSE)
            } else {
              #write.table(y_row, paste("C:/Users/cshar/OneDrive - University of Florida/Online_diss_files/Ch2/Large files/Results/y/", title_use, ".csv", sep=""), row.names=FALSE, col.names=FALSE, append=TRUE)
              write.table(y_row, paste("/blue/carpena/caseyharris/Ch2/Results/y/", title_use, ".csv", sep=""), row.names=FALSE, col.names=FALSE, append=TRUE)
            }
          } #very slow, like 8 hours per water quality parameter...
        }
stopCluster(cl = cluster)

#for flow values not in the observed range

#check <- read.table(paste("C:/Users/cshar/OneDrive - University of Florida/Online_diss_files/Ch2/Large files/Results/y/", title_use, ".csv", sep=""), header=TRUE)
#check <- read.table(paste("/blue/carpena/caseyharris/Ch2/Results/y/", title_use, ".csv", sep=""), header=TRUE)